[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
ast = true
build_info = true
extra_output = ["abi", "evm.bytecode"]

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

# Formatter
fmt = { line_length = 120, tab_width = 4, bracket_spacing = true }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
