name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          forge install --no-commit

      - name: Build contracts
        run: forge build --sizes

      - name: Run tests
        run: forge test -vvv --no-match-test invariant
        continue-on-error: true

      - name: Gas report
        run: forge test --gas-report --no-match-test invariant
        continue-on-error: true

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: forge install --no-commit

      - uses: crytic/slither-action@v0.4.0
        with:
          fail-on: high
          slither-args: --exclude-dependencies
        continue-on-error: true
